# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtle_battle/GameState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GameState(genpy.Message):
  _md5sum = "0051aa3ff6623e54a13e3a5509f76a87"
  _type = "turtle_battle/GameState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 turtle1_health
int32 turtle2_health
int32 turtle1_attacks_remaining
int32 turtle2_attacks_remaining
"""
  __slots__ = ['turtle1_health','turtle2_health','turtle1_attacks_remaining','turtle2_attacks_remaining']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       turtle1_health,turtle2_health,turtle1_attacks_remaining,turtle2_attacks_remaining

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GameState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.turtle1_health is None:
        self.turtle1_health = 0
      if self.turtle2_health is None:
        self.turtle2_health = 0
      if self.turtle1_attacks_remaining is None:
        self.turtle1_attacks_remaining = 0
      if self.turtle2_attacks_remaining is None:
        self.turtle2_attacks_remaining = 0
    else:
      self.turtle1_health = 0
      self.turtle2_health = 0
      self.turtle1_attacks_remaining = 0
      self.turtle2_attacks_remaining = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.turtle1_health, _x.turtle2_health, _x.turtle1_attacks_remaining, _x.turtle2_attacks_remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.turtle1_health, _x.turtle2_health, _x.turtle1_attacks_remaining, _x.turtle2_attacks_remaining,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.turtle1_health, _x.turtle2_health, _x.turtle1_attacks_remaining, _x.turtle2_attacks_remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.turtle1_health, _x.turtle2_health, _x.turtle1_attacks_remaining, _x.turtle2_attacks_remaining,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
